# Docker Compose use for production Compose config file environment setup
# AWS EBS will see a file named docker-compose.yml and use it to build the single container application.
version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    # Port map Important for AWS hosting '80:80' pattern 
      - '80:80'