# syntax=docker/dockerfile:1.4
# Create image based on the official Node image from dockerhub
# This image only use for development environment setup
FROM node:18-alpine

# Create app directory
WORKDIR '/app'

# Copy dependency definitions
COPY ./package.json /app
COPY ./package-lock.json /app
# Install dependecies
RUN npm install
# Get all the code needed to run the app
COPY ./ /app

# Expose the port the app runs in
EXPOSE 3000

# Serve the app
CMD ["npm", "run", "start"]
