# https://docs.docker.com/build/ci/github-actions/#get-started-with-github-actions
name: Builds and push to the Docker Hub repository CI
on:
  push:
    branches: ['main']
env:
  TEST_TAG: ${{ secrets.DOCKERHUB_USERNAME }}/docker-react-apps-deployment:test
  DEVELOPMENT_TAG: ${{ secrets.DOCKERHUB_USERNAME }}/docker-react-apps-deployment:test

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks out the repository on the build machine.
      - name: Checkout source code
        uses: actions/checkout@v4

      # Signs in to Docker Hub, using the Docker Login action and your Docker Hub credentials.
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Creates a BuildKit builder instance using the Docker Setup Buildx action.
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Test before push with GitHub Actions
      - name: Build and export to Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.dev
          load: true
          tags: ${{ env.TEST_TAG }}
      - name: Test run
        run: |
          docker run -e CI=true ${{ env.TEST_TAG }} npm run test

      # Builds the container image and push it to the Docker Hub repository, using Build and push Docker images
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          # the build context.
          context: .
          # filepath to the Dockerfile.
          file: ./Dockerfile.dev
          # tells the action to upload the image to a registry after building it
          push: true
          # tags that specify where to push the image.
          tags: ${{ env.DEVELOPMENT_TAG }}