# https://docs.docker.com/build/ci/github-actions/#get-started-with-github-actions
name: Deploy apps to AWS Elastic Beanstalk CI
on:
  push:
    branches: ['main']
env:
  TEST_TAG: ${{ secrets.DOCKERHUB_USERNAME }}/docker-react-apps-deployment:test
  DEVELOPMENT_TAG: ${{ secrets.DOCKERHUB_USERNAME }}/docker-react-apps-deployment:latest

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks out the repository on the build machine.
      - name: Checkout source code
        uses: actions/checkout@v4

      # Signs in to Docker Hub, using the Docker Login action and your Docker Hub credentials.
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Creates a BuildKit builder instance using the Docker Setup Buildx action.
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Test before push with GitHub Actions
      - name: Build and export to Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.dev
          load: true
          tags: ${{ env.TEST_TAG }}
      - name: Test run
        run: |
          docker run -e CI=true ${{ env.TEST_TAG }} npm run test

      # Builds the container image by development env setup.
      - name: Build the image
        uses: docker/build-push-action@v5
        with:
          # the build context.
          context: .
          # filepath to the Dockerfile.
          file: ./Dockerfile.dev
          # tells the action to upload the image to a registry after building it
          push: false
          # tags that specify where to push the image.
          tags: ${{ env.DEVELOPMENT_TAG }}
      # https://github.com/einaregilsson/beanstalk-deploy
      # Beanstalk Deploy is a GitHub action (and command line script) to deploy apps to AWS Elastic Beanstalk. 
      # It takes the application name, environment name, version name, region and filename as parameters, uploads the file to S3, creates a new version in Elastic Beanstalk, and then deploys that version to the environment.
      # Beanstalk Deploy, Using as a GitHub Action
      # Generate deployment package
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      # Beanstalk Deploy
      
      - name: Deploy apps to AWS Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: docker-react-apps-deployment
          environment_name: Docker-react-apps-deployment-env
          existing_bucket_name: elasticbeanstalk-ap-northeast-1-734549988040
          version_description: ${{github.SHA}}
          version_label: ${{ github.sha }}
          region: ap-northeast-1
          deployment_package: deploy.zip
