# https://docs.docker.com/build/ci/github-actions/#get-started-with-github-actions
name: Development ENV Build CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
       # Checks out the repository on the build machine.
       - name: Checkout
         uses: actions/checkout@v4

      # Signs in to Docker Hub, using the Docker Login action and your Docker Hub credentials.
       - name: Login to Docker Hub
         uses: docker/login-action@v3
         with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Creates a BuildKit builder instance using the Docker Setup Buildx action.
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v3

      # Builds the container image and pushes it to the Docker Hub repository, using Build and push Docker images.
       - name: Build the image
         uses: docker/build-push-action@v5
         with:
          # the build context.
          context: .
          # filepath to the Dockerfile.
          file: ./Dockerfile.dev
          # tells the action to upload the image to a registry after building it
          push: false
          # tags that specify where to push the image.
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/docker-react-apps-deployment:latest
