name: Development build CI
on:
    push:
      branches: [ "main" ]
jobs: 
    build: 
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }} 
            - name: Build the Docker image
              run: docker build . --file Dockerfile.dev --tag ${{ secrets.DOCKERHUB_USERNAME }}/docker-react-apps-deployment:latest
            


